---
- name: Converge
  hosts: all
  become: true

  vars:
    # Role: rhsm
    rhsm_username: "{{ lookup('env', 'RHSM_USERNAME') }}"
    rhsm_password: "{{ lookup('env', 'RHSM_PASSWORD') }}"
    rhsm_auto_attach: true
    rhsm_server_proxy_hostname: "{{ lookup('env', 'http_proxy_hostname') }}"
    rhsm_server_proxy_port: "{{ lookup('env', 'http_proxy_port') }}"
    rhsm_server_proxy_user: "{{ lookup('env', 'http_proxy_user') }}"
    rhsm_server_proxy_password: "{{ lookup('env', 'http_proxy_password') }}"
    rhsm_consumer_name: "nycrecords_{{ '%Y%m%d_%H%M%s' | strftime(ansible_date_time.epoch) }}"

    # Role: yum_config_manager
    repositories:
      enabled:
        - rhui-REGION-rhel-server-rhscl
        - rhui-REGION-rhel-server-debug-rhscl

    # Role: ruby
    ruby_install_from_source: false
    ruby_packages:
      - rh-ruby25
      - rh-ruby25-ruby-devel
      - rh-ruby25-ruby-bundler
      - "{{ ruby_rubygems_package_name }}"
      - '@development'
    ruby_scl_package: rh-ruby25
    ruby_use_scl: true
    ruby_install_bundler: true

  roles:
    - role: nycrecords.yum_config_manager
      when: molecule_yml.driver.name == "ec2"
    - role: nycrecords.rhsm
      when: molecule_yml.driver.name == "vagrant"
    - role: ansible-role-ruby
